version: '3.9'

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"           # HTTP 入口
      - "1883:1883"       # MQTT (TCP) 入口
      - "8888:8888/udp"   # UDP 设备发现入口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/web-pages/default
      - ../app/ahoh-plane/dist:/web-pages/ahoh-plane
    restart: on-failure

  mqtt-broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: on-failure
    # 内部声明监听端口（仅用于内部通信）
    expose:
      - "1883"

  api:
    build: ./http-api
    restart: on-failure
    expose:
      - "18080"
      - "8888/udp"

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mqttdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: on-failure
    expose:
      - "5432"
