version: '3'
services:
    reverse-proxy:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./html:/web-pages/default
        - ../app/ahoh-plane/dist:/web-pages/ahoh-plane
      restart: on-failure:3
      depends_on:
        - mqtt-broker
        - api
      #  - database
      #  - cache
    
    mqtt-broker:
      image: eclipse-mosquitto:latest
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      ports:
        - "1883:1883"
      restart: on-failure:3

    api:
      build: ./http-api
      restart: on-failure:3
      #depends_on:
      #  - database
      #  - cache

    db:
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: mqttdb
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      ports:
        - "5432:5432"
      restart: on-failure:3

    #cache: 
    #  image: redis:latest
    #  restart: on-failure:3

