FROM alpine:3.19 AS builder
RUN apk add --no-cache \
    build-base \
    cmake \
    spdlog-dev \
    boost-dev \
    openssl-dev \
    libpq-dev \
    linux-headers
WORKDIR /app
COPY . .
RUN mkdir build && cd build && \
    cmake .. && make -j$(nproc)

FROM alpine:3.19
RUN apk add --no-cache \
    libstdc++ \
    libpq \
    spdlog \
    boost \
    openssl
COPY --from=builder /app/build/ahoh-http-server /usr/local/bin/
CMD ["ahoh-http-server"]